## date format used, either "us" or "uk"
dialect = "uk"

## enable or disable automatic update checks
update_check = false

## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
search_mode = "fuzzy"

## which style to use
## possible values: auto, full, compact
style = "full"

## the maximum number of lines the interface should take up
## set it to 0 to always go full screen
inline_height = 0

## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
exit_mode = "return-query"
