default_flags = "gh"
show_selection_mark = true
[skin]
default = "gray(23) none / gray(20) none"
[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "/opt/homebrew/bin/nvim +{line} {file}"
leave_broot = false
