local wezterm = require("wezterm")
-- return wezterm.font("GeistMono Nerd Font")
-- return wezterm.font("Hack Nerd Font")
-- return wezterm.font("Hasklug Nerd Font")
-- return wezterm.font("Monofur Nerd Font")
return wezterm.font("Hurmit Nerd Font")
-- return wezterm.font("FiraCode Nerd Font")
-- return wezterm.font("Agave Nerd Font")
-- return wezterm.font("Mononoki Nerd Font")
-- return wezterm.font("Overpass Nerd Font")
