local wezterm = require("wezterm")
-- font = wezterm.font("Fira Code")
-- font = wezterm.font("Hurmit Nerd Font")
-- font = wezterm.font("FiraCode Nerd Font")
return wezterm.font("Mononoki Nerd Font")
-- font = wezterm.font("JetBrains Mo")
