# Disable ctrl-s
stty stop undef

# Export vars
export SRC_ENDPOINT="https://sourcegraph.com"
export EDITOR="nvim"
export ANTHROPIC_API_KEY="$(< /run/secrets/anthropic_api_key)"
export HYPRSHOT_DIR="/home/daniel/screenshots/"

# Aliases
alias v=nvim
alias g=lazygit
alias c=clear
alias y=yazi
alias rm=trash
alias ls=exa
ff() { du -a | awk '{print $2}' | $(fzf --height 40% --border)| xargs -r $EDITOR ; }

h() {
  history -n -1000 | awk '!a[$0]++' | fzf --height 40% --border | wl-copy
}

take() {mkdir -p $1 ; cd $1 ; }
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

HISTSIZE=100000
SAVEHIST=100000
setopt HIST_SAVE_NODUPS

source ~/zsh_modules/zsh-vi-mode.zsh

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(direnv hook zsh)"
