[als.time]
thresholds = { 0 = "night", 8 = "day", 18 = "night" }

[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/intel_backlight"
capturer = "wlroots"
[output.backlight.predictor.manual]
thresholds.day = { 0 = 0, 100 = 90 }    # luma = reduction %
thresholds.night = { 0 = 0, 100 = 60 }
