{ inputs, ... }:
let
  themes = import ./themes;
in
{
  imports = [ inputs.nix-colors.homeManagerModules.default ];

  # Hand-rolled, in ./themes
  colorScheme = themes.driftwood; # warm sand and taupe
  # colorScheme = themes.harbour; # cool blue slate
  # colorScheme = themes.fernglow; # soft forest green
  # colorScheme = themes.plumsmoke; # muted violet
  # colorScheme = themes.graphite; # neutral charcoal
  # colorScheme = themes.crosswire; # red and green swapped
  # colorScheme = themes.seaglass; # cool slots doing warm work, one hot red
  # colorScheme = themes.bruise; # hues rotated half a turn

  # https://github.com/tinted-theming/base16-schemes
  # colorScheme = inputs.nix-colors.colorSchemes.kanagawa;
  # colorScheme = inputs.nix-colors.colorSchemes.ashes;
  # colorScheme = inputs.nix-colors.colorSchemes.atelier-cave;
  # colorScheme = inputs.nix-colors.colorSchemes.atelier-forest; # 6/10
  # colorScheme = inputs.nix-colors.colorSchemes.atlas; # 5/10
  # colorScheme = inputs.nix-colors.colorSchemes.ayu-dark; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.blueforest; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.catppuccin-mocha; # 8/10
  # colorScheme = inputs.nix-colors.colorSchemes.codeschool;  # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.danqing; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.darcula; # 6/10
  # colorScheme = inputs.nix-colors.colorSchemes.darkmoss; # 8/10
  # colorScheme = inputs.nix-colors.colorSchemes.darktooth; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.decaf; # 6/10
  # colorScheme = inputs.nix-colors.colorSchemes.dracula; # 8/10
  # colorScheme = inputs.nix-colors.colorSchemes.eighties; # 6/10
  # colorScheme = inputs.nix-colors.colorSchemes.eris; # 6/10
  # colorScheme = inputs.nix-colors.colorSchemes.espresso; # 6/10
  # colorScheme = inputs.nix-colors.colorSchemes.eva; # 8/10
  # colorScheme = inputs.nix-colors.colorSchemes.everforest; # 9/10
  # colorScheme = inputs.nix-colors.colorSchemes.flat; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.gigavolt; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.google-dark; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.gotham; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.gruber; # 8/10
  # colorScheme = inputs.nix-colors.colorSchemes.gruvbox-dark-hard; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.hardcore; # 7/10 borders not clear
  # colorScheme = inputs.nix-colors.colorSchemes.harmonic16-dark; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.hopscotch; # 8/10
  # colorScheme = inputs.nix-colors.colorSchemes.horizon-dark; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.humanoid-dark; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.kanagawa; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.katy; # 8/10 very blue
  # colorScheme = inputs.nix-colors.colorSchemes.materia; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.material; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.material-darker; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.material-palenight; # 8/10 quite blue/gray
  # colorScheme = inputs.nix-colors.colorSchemes.mellow-purple; # 7/10 very very very purple
  # colorScheme = inputs.nix-colors.colorSchemes.monokai;
  # colorScheme = inputs.nix-colors.colorSchemes.nebula; # 7/10 Very blue
  # colorScheme = inputs.nix-colors.colorSchemes.nord; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.nova; # 8/10
  # colorScheme = inputs.nix-colors.colorSchemes.oceanicnext # 8/10;
  # colorScheme = inputs.nix-colors.colorSchemes.one-light;
  # colorScheme = inputs.nix-colors.colorSchemes.onedark; # 8/10;
  # colorScheme = inputs.nix-colors.colorSchemes.paraiso; # 8/10;
  # colorScheme = inputs.nix-colors.colorSchemes.pasque; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.phd; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.pinky; # 8/10 really nice but too dark bg
  # colorScheme = inputs.nix-colors.colorSchemes.porple; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.primer-dark-dimmed; # 7/10
  # colorScheme = inputs.nix-colors.colorSchemes.railscasts;
  # colorScheme = inputs.nix-colors.colorSchemes.rebecca; # 6.5 Intensely blue/violet
  # colorScheme = inputs.nix-colors.colorSchemes.rose-pine; # 8
  # colorScheme = inputs.nix-colors.colorSchemes.rose-pine-moon; # 9 lighter bg
  # colorScheme = inputs.nix-colors.colorSchemes.sakura;
  # colorScheme = inputs.nix-colors.colorSchemes.sandcastle; # 9 Sandy but cool
  # colorScheme = inputs.nix-colors.colorSchemes.selenized-black;
  # colorScheme = inputs.nix-colors.colorSchemes.selenized-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.selenized-light;
  # colorScheme = inputs.nix-colors.colorSchemes.selenized-white;
  # colorScheme = inputs.nix-colors.colorSchemes.seti;
  # colorScheme = inputs.nix-colors.colorSchemes.shades-of-purple;
  # colorScheme = inputs.nix-colors.colorSchemes.shadesmear-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.shadesmear-light;
  # colorScheme = inputs.nix-colors.colorSchemes.shapeshifter;
  # colorScheme = inputs.nix-colors.colorSchemes.silk-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.silk-light;
  # colorScheme = inputs.nix-colors.colorSchemes.snazzy;
  # colorScheme = inputs.nix-colors.colorSchemes.solarflare;
  # colorScheme = inputs.nix-colors.colorSchemes.solarflare-light;
  # colorScheme = inputs.nix-colors.colorSchemes.solarized-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.solarized-light;
  # colorScheme = inputs.nix-colors.colorSchemes.spaceduck;
  # colorScheme = inputs.nix-colors.colorSchemes.spacemacs;
  # colorScheme = inputs.nix-colors.colorSchemes.standardized-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.standardized-light;
  # colorScheme = inputs.nix-colors.colorSchemes.stella;
  # colorScheme = inputs.nix-colors.colorSchemes.still-alive;
  # colorScheme = inputs.nix-colors.colorSchemes.summercamp;
  # colorScheme = inputs.nix-colors.colorSchemes.summerfruit-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.summerfruit-light;
  # colorScheme = inputs.nix-colors.colorSchemes.synth-midnight-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.synth-midnight-light;
  # colorScheme = inputs.nix-colors.colorSchemes.tango;
  # colorScheme = inputs.nix-colors.colorSchemes.tarot;
  # colorScheme = inputs.nix-colors.colorSchemes.tender;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyo-city-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyo-city-light;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyo-city-terminal-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyo-city-terminal-light;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyo-night-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyo-night-light;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyo-night-storm;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyo-night-terminal-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyo-night-terminal-light;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyo-night-terminal-storm;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyodark;
  # colorScheme = inputs.nix-colors.colorSchemes.tokyodark-terminal;
  # colorScheme = inputs.nix-colors.colorSchemes.tomorrow;
  # colorScheme = inputs.nix-colors.colorSchemes.tomorrow-night;
  # colorScheme = inputs.nix-colors.colorSchemes.tomorrow-night-eighties;
  # colorScheme = inputs.nix-colors.colorSchemes.tube;
  # colorScheme = inputs.nix-colors.colorSchemes.twilight;
  # colorScheme = inputs.nix-colors.colorSchemes.unikitty-dark;
  # colorScheme = inputs.nix-colors.colorSchemes.unikitty-light;
  # colorScheme = inputs.nix-colors.colorSchemes.unikitty-reversible;
  # colorScheme = inputs.nix-colors.colorSchemes.uwunicorn;
  # colorScheme = inputs.nix-colors.colorSchemes.vice;
  # colorScheme = inputs.nix-colors.colorSchemes.vulcan;
  # colorScheme = inputs.nix-colors.colorSchemes.windows-10;
  # colorScheme = inputs.nix-colors.colorSchemes.windows-10-light;
  # colorScheme = inputs.nix-colors.colorSchemes.windows-95;
  # colorScheme = inputs.nix-colors.colorSchemes.windows-95-light;
  # colorScheme = inputs.nix-colors.colorSchemes.windows-highcontrast;
  # colorScheme = inputs.nix-colors.colorSchemes.windows-highcontrast-light;
  # colorScheme = inputs.nix-colors.colorSchemes.windows-nt;
  # colorScheme = inputs.nix-colors.colorSchemes.windows-nt-light;
  # colorScheme = inputs.nix-colors.colorSchemes.woodland;
  # colorScheme = inputs.nix-colors.colorSchemes.xcode-dusk;
  # colorScheme = inputs.nix-colors.colorSchemes.zenbones;
  # colorScheme = inputs.nix-colors.colorSchemes.zenburn;
}
