[font]
normal = { family = "Hack Nerd Font" } 
builtin_box_drawing = false
size = 30

[window]
padding = { x = 20, y = 20 }
dynamic_padding = true
opacity = 1

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{key = "Plus", mods = "Control|Shift", action = "IncreaseFontSize"} # QMK inputs "Control|Shift Equals" when you try to "Control Plus". For some reason this fixes it.
]
