# A minimal left prompt
format = """$character"""

# move the rest of the prompt to the right
right_format = """$all"""# Get editor completions based on the config schema

"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[package]
disabled = true

[cmd_duration]
disabled = true

# Nerd fonts
[aws]
symbol = "  "

[buf]
symbol = " "
[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[direnv]
disabled = true

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_status]
disabled = true

[golang]
symbol = " "
format = '[$symbol]($style)'
style = 'bold purple'

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "
format = '[$symbol]($style)'
style = 'bold purple'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "
format = '[$symbol]($style)'
style = 'bold purple'

[nodejs]
symbol = " "
format = '[$symbol]($style)'
style = 'bold purple'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

# [package]
# symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "
format = '[$symbol$virtualenv ]($style)'
style = 'bold purple'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "
format = '[$symbol]($style)'
style = 'bold purple'

[scala]
symbol = " "

[git_branch]
symbol = " "
always_show_remote = true
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'bold purple'

