return {
  --  ╭──────────────────────────────────────────────────────────╮
  --  │                       nvim-base16                        │
  --  ╰──────────────────────────────────────────────────────────╯
  {
    "rrethy/nvim-base16",
    lazy = false,
    config = function()
      vim.cmd("colorscheme base16-woodland")
    end,
  },
  --  ╭──────────────────────────────────────────────────────────╮
  --  │                       transparent                        │
  --  ╰──────────────────────────────────────────────────────────╯
  {
    "xiyaowong/transparent.nvim",
    lazy = false,
    dependencies = {
      "lewis6991/gitsigns.nvim",
    },
    opts = {
      groups = {
        -- "Must haves"
        "Normal",
        "NormalNC",
        "SignColumn",

        "VertSplit",
        "StatusLine",
        "Comment",
        "Constant",
        "Special",
        "Identifier",
        "Statement",
        "PreProc",
        "Type",
        "Title",
        "Underlined",
        "Todo",
        "String",
        "Function",
        "FloatTitle",
        "FloatShadow",
        "FloatShadowThrough",
        "Conditional",
        "Repeat",
        "Operator",
        "Structure",
        "LineNr",
        "NonText",
        "CursorLineNr",
        "EndOfBuffer",
        "MsgSeparator",
      },

      extra_groups = {
        -- Plugins which have float panel such as Lazy, Mason, LspInfo
        -- "NormalFloat",
        -- "FloatBorder",

        -- Telescope
        -- "TelescopeNormal",
        -- "TelescopeMatching",
        -- "TelescopeSelection",
        -- "TelescopePromptNormal",
        -- -- "TelescopePromptBorder",
        -- "TelescopePromptTitle",
        -- "TelescopePromptPrefix",
        -- -- "TelescopeResultsBorder",
        -- "TelescopeResultsNormal",
        -- "TelescopeResultsTitle",
        -- -- "TelescopePreviewBorder",
        -- "TelescopePreviewNormal",
        -- "TelescopePreviewTitle",
        -- "TelescopeResultsDiffChange",
        -- "TelescopeResultsDiffAdd",
        -- "TelescopeResultsDiffDelete",
        -- "TelescopeSelectionCaret",

        -- GitSigns
        "GitSignsChange",
        "GitSignsAdd",
        "GitSignsDelete",
        "GitSignsAddLine",

        -- Which key
        -- "WhichKeyFloat",
        -- "WhichKeyBorder",

        -- Diagnostics
        "DiagnosticSignError",
        "DiagnosticSignWarn",
        "DiagnosticSignHint",
        "DiagnosticSignInfo",

        -- Barbecue
        "barbecue_normal",

        "NeoTreeBufferNumber",
        "NeoTreeCursorLine",
        "NeoTreeDimText",
        "NeoTreeDirectoryIcon",
        "NeoTreeDirectoryName",
        "NeoTreeDotfile",
        "NeoTreeFadeText1",
        "NeoTreeFadeText2",
        "NeoTreeFileIcon",
        "NeoTreeFileName",
        "NeoTreeFileNameOpened",
        "NeoTreeFileStats",
        "NeoTreeFileStatsHeader",
        "NeoTreeFilterTerm",
        "NeoTreeFloatBorder",
        "NeoTreeFloatNormal",
        "NeoTreeFloatTitle",
        "NeoTreeGitAdded",
        "NeoTreeGitConflict",
        "NeoTreeGitDeleted",
        "NeoTreeGitIgnored",
        "NeoTreeGitModified",
        "NeoTreeGitRenamed",
        "NeoTreeGitStaged",
        "NeoTreeGitUntracked",
        "NeoTreeGitUnstaged",
        "NeoTreeHiddenByName",
        "NeoTreeIndentMarker",
        "NeoTreeMessage",
        "NeoTreeModified",
        "NeoTreeNormal",
        "NeoTreeNormalNC",
        "NeoTreeSignColumn",
        "NeoTreeStatusLine",
        "NeoTreeStatusLineNC",
        "NeoTreeTabActive",
        "NeoTreeTabInactive",
        "NeoTreeTabSeparatorActive",
        "NeoTreeTabSeparatorInactive",
        "NeoTreeVertSplit",
        "NeoTreeWinSeparator",
        "NeoTreeEndOfBuffer",
        "NeoTreeRootName",
        "NeoTreeSymbolicLinkTarget",
        "NeoTreeTitleBar",
        "NeoTreeIndentMarker",
        "NeoTreeExpander",
        "NeoTreeWindowsHidden",
        "NeoTreePreview",

        -- Bqf
        -- "BqfPreviewFloat", -- Doesn't work?
        -- "BqfPreviewBorder",
        -- "BqfPreviewTitle",
        -- "BqfPreviewThumb",
        -- "BqfPreviewSbar",
        -- "BqfPreviewCursor",
        -- "BqfPreviewCursorLine",
        -- "BqfPreviewRange",
        -- "BqfPreviewBufLabel",

        -- Noice
        -- "NoicePopupmenu",
        -- "NoiceScrollbar",
        -- "NoiceFormatConfirm",
        -- "NoiceScrollbarThumb",

        -- Lualine
        "lualine_b_insert",
        "lualine_b_normal",
        "lualine_b_replace",
        "lualine_b_command",
        "lualine_b_terminal",
        "lualine_b_inactive",
        "lualine_b_visual",
        "lualine_c_insert",
        "lualine_c_normal",
        "lualine_c_replace",
        "lualine_c_command",
        "lualine_c_terminal",
        "lualine_c_inactive",
        "lualine_c_visual",
        "lualine_c_diagnostics_warn_insert",
        "lualine_c_diagnostics_warn_normal",
        "lualine_c_diagnostics_warn_replace",
        "lualine_c_diagnostics_warn_command",
        "lualine_c_diagnostics_warn_terminal",
        "lualine_c_diagnostics_warn_inactive",
        "lualine_c_diagnostics_warn_visual",
        "lualine_c_diagnostics_info_insert",
        "lualine_c_diagnostics_info_normal",
        "lualine_c_diagnostics_info_replace",
        "lualine_c_diagnostics_info_command",
        "lualine_c_diagnostics_info_terminal",
        "lualine_c_diagnostics_info_inactive",
        "lualine_c_diagnostics_info_visual",
        "lualine_c_diagnostics_error_insert",
        "lualine_c_diagnostics_error_normal",
        "lualine_c_diagnostics_error_replace",
        "lualine_c_diagnostics_error_command",
        "lualine_c_diagnostics_error_terminal",
        "lualine_c_diagnostics_error_inactive",
        "lualine_c_diagnostics_error_visual",
        "lualine_c_diagnostics_hint_insert",
        "lualine_c_diagnostics_hint_normal",
        "lualine_c_diagnostics_hint_replace",
        "lualine_c_diagnostics_hint_command",
        "lualine_c_diagnostics_hint_terminal",
        "lualine_c_diagnostics_hint_inactive",
        "lualine_c_diagnostics_hint_visual",
      },
    },
  },
}
