[zsh.files]
"zsh" = { target = "~", type = "symbolic" }

[starship.files]
"starship.toml" = { target = "~/.config/starship.toml", type = "symbolic" }

[yabai.files]
"yabairc" = { target = "~/.config/yabai/yabairc", type = "symbolic" }

[skhd.files]
"skhdrc" = { target = "~/.config/skhd/skhdrc", type = "symbolic" }

[git.files]
".gitconfig" = { target = "~/.gitconfig", type = "symbolic" }

[lazygit.files]
"lazygit.yml" = { target = "~/Library/Application Support/lazygit/config.yml", type = "symbolic" }

[nushell.files]
"nushell" = { target = "~/Library/Application Support/nushell", type = "symbolic" }

[neovim.files]
"nvim" = { target = "~/.config/nvim", type = "symbolic" }

[alacritty.files]
"alacritty.yml" = { target = "~/.config/alacritty/alacritty.yml", type = "symbolic" }

[xplr.files]
"xplr.lua" = { target = "~/.config/xplr/init.lua", type = "symbolic" }

[atuin.files]
"atuin.toml" = { target = "~/.config/atuin/config.toml", type = "symbolic" }

[tmux.files]
"tmux" = { target = "~/.config/tmux", type = "symbolic" }

[kitty.files]
"kitty.conf" = { target = "~/.config/kitty/kitty.conf", type = "symbolic" }

[wezterm.files]
"wezterm.lua" = { target = "~/.config/wezterm/wezterm.lua", type = "symbolic" }
